"""empty message

Revision ID: 1fa8fd2f462a
Revises: 73f693ccbe0a
Create Date: 2022-04-08 12:13:20.480719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1fa8fd2f462a"
down_revision = "73f693ccbe0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gsuser", schema=None) as batch_op:
        batch_op.create_foreign_key("gsuidbr", "users", ["uid"], ["id"])

    op.drop_table("pokemon")
    op.drop_table("dream_poke")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pokemon", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gsuser_id", sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, "gsuser", ["gsuser_id"], ["id"])

    with op.batch_alter_table("gsuser", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
    op.create_table("dreampoke")
    # ### end Alembic commands ###
