"""empty message

Revision ID: 311548b3bf94
Revises: 
Create Date: 2021-10-02 19:28:02.719978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "311548b3bf94"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gsuser",
        sa.Column("id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pokemon",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dexno", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("exp", sa.Integer(), nullable=True),
        sa.Column("iv_hp", sa.Integer(), nullable=True),
        sa.Column("iv_atk", sa.Integer(), nullable=True),
        sa.Column("iv_def", sa.Integer(), nullable=True),
        sa.Column("iv_spatk", sa.Integer(), nullable=True),
        sa.Column("iv_spdef", sa.Integer(), nullable=True),
        sa.Column("iv_speed", sa.Integer(), nullable=True),
        sa.Column("ev_hp", sa.Integer(), nullable=True),
        sa.Column("ev_atk", sa.Integer(), nullable=True),
        sa.Column("ev_def", sa.Integer(), nullable=True),
        sa.Column("ev_spatk", sa.Integer(), nullable=True),
        sa.Column("ev_spdef", sa.Integer(), nullable=True),
        sa.Column("ev_speed", sa.Integer(), nullable=True),
        sa.Column("nature", sa.String(), nullable=True),
        sa.Column("ability", sa.String(), nullable=True),
        sa.Column("item", sa.String(), nullable=True),
        sa.Column("move1", sa.String(), nullable=True),
        sa.Column("move2", sa.String(), nullable=True),
        sa.Column("move3", sa.String(), nullable=True),
        sa.Column("move4", sa.String(), nullable=True),
        sa.Column("gsuser_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gsuser_id"],
            ["gsuser.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pokemon")
    op.drop_table("gsuser")
    # ### end Alembic commands ###
