"""empty message

Revision ID: 773806d65e13
Revises: 311548b3bf94
Create Date: 2021-10-09 10:30:05.544899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773806d65e13'
down_revision = '311548b3bf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsuser', sa.Column('gsid', sa.Integer(), nullable=True))
    op.add_column('gsuser', sa.Column('name', sa.String(length=7), nullable=True))
    op.add_column('gsuser', sa.Column('poke_is_sleeping', sa.Boolean(), nullable=True))
    op.add_column('gsuser', sa.Column('tid', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'gsuser', ['gsid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gsuser', type_='unique')
    op.drop_column('gsuser', 'tid')
    op.drop_column('gsuser', 'poke_is_sleeping')
    op.drop_column('gsuser', 'name')
    op.drop_column('gsuser', 'gsid')
    # ### end Alembic commands ###
