"""empty message

Revision ID: a24ed513d3b0
Revises: b3960d6e8757
Create Date: 2022-04-06 13:04:27.957336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24ed513d3b0'
down_revision = 'b3960d6e8757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsuser', 'gsid')
    # ### end Alembic commands ###
    op.drop_constraint(None, 'gsuser', type_='unique')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsuser', sa.Column('gsid', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
