"""empty message

Revision ID: b3960d6e8757
Revises: b6a9459733f2
Create Date: 2022-04-06 13:03:48.393755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3960d6e8757'
down_revision = 'b6a9459733f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'gsuser', ['tid'])
    op.drop_column('gsuser', 'gsid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsuser', sa.Column('gsid', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'gsuser', type_='unique')
    # ### end Alembic commands ###
