"""empty message

Revision ID: b43ee1cdb99b
Revises: 1fa8fd2f462a
Create Date: 2022-04-08 12:25:07.220945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b43ee1cdb99b"
down_revision = "1fa8fd2f462a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gsuser", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uid", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("usertogslink", "users", ["uid"], ["id"])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("ix_users_email")
        batch_op.drop_index("ix_users_username")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("ix_users_username", ["username"], unique=False)
        batch_op.create_index("ix_users_email", ["email"], unique=False)

    with op.batch_alter_table("gsuser", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("uid")

    # ### end Alembic commands ###
