"""empty message

Revision ID: b6a9459733f2
Revises: 773806d65e13
Create Date: 2022-04-04 21:13:20.978950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a9459733f2'
down_revision = '773806d65e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsuser', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('gsuser', sa.Column('gamever', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'gsuser', ['gsid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gsuser', type_='unique')
    op.drop_column('gsuser', 'gamever')
    op.drop_column('gsuser', 'gender')
    # ### end Alembic commands ###
