"""empty message

Revision ID: c062311c1c52
Revises: 2218a1d4c654
Create Date: 2022-08-17 14:37:16.933232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c062311c1c52"
down_revision = "2218a1d4c654"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gsuser", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pokemon0", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon1", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon2", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon3", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon4", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon5", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon6", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon7", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon8", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("pokemon9", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("gsuser", schema=None) as batch_op:
        batch_op.drop_column("pokemon9")
        batch_op.drop_column("pokemon8")
        batch_op.drop_column("pokemon7")
        batch_op.drop_column("pokemon6")
        batch_op.drop_column("pokemon5")
        batch_op.drop_column("pokemon4")
        batch_op.drop_column("pokemon3")
        batch_op.drop_column("pokemon2")
        batch_op.drop_column("pokemon1")
        batch_op.drop_column("pokemon0")

    # ### end Alembic commands ###
