"""empty message

Revision ID: d01fc829c8c2
Revises: 
Create Date: 2021-10-29 13:57:12.013574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01fc829c8c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsuser', sa.Column('password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsuser', 'password_hash')
    # ### end Alembic commands ###
