"""empty message

Revision ID: fab202fb317c
Revises: 311548b3bf94
Create Date: 2021-10-09 10:28:50.768854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab202fb317c'
down_revision = '311548b3bf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsuser', sa.Column('gsid', sa.Integer(), nullable=False))
    op.add_column('gsuser', sa.Column('name', sa.String(length=7), nullable=True))
    op.add_column('gsuser', sa.Column('poke_is_sleeping', sa.Boolean(), nullable=True))
    op.add_column('gsuser', sa.Column('tid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gsuser', 'tid')
    op.drop_column('gsuser', 'poke_is_sleeping')
    op.drop_column('gsuser', 'name')
    op.drop_column('gsuser', 'gsid')
    # ### end Alembic commands ###
